In [1]:
import numpy as np   #numpy makes our analysis , calculation and statistics part easier thats'why we use Numpy for analysis of data

#### How to create an array

In [2]:
a=np.array([1,2,3,4,5])  #list and array are almost same with only difference that there in array only same type of elements can be stored
b= np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)  # ndarray--> nth- dimensional array

numpy.ndarray

### Basic operations of Array

In [4]:
print(a+b)   #adding array elements
print(a-b)   #subtracting array elements
print(a*b)   #multiplying array elements

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [5]:
# creating 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [6]:
# creating 3D array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
print(a2.shape)
print(a3.shape) # two 2d arrays with 2 rows and 3 columns

(2, 3)
(2, 2, 3)


In [8]:
print(a2.ndim) # ndim--> to check dimentions of array
print(a3.ndim)

2
3


In [9]:
# creating a 4d array
a4 =np.array([[[[1,2],[3,4,]],
               [[5,6],[7,8]]],
              [[[9,10],[11,12]],
               [[13,14],[15,16]]]])
print(a4)
print(a4.shape)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
(2, 2, 2, 2)


In [10]:
print(a2.dtype)

int64


In [11]:
# arange() is used to create an array according to (start,stop,step) values similar to range()
np.arange(11)  #11 as it will count till 10 only(like range() 1 stop value is excluded)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
np.random.randint(1,11, size=(3,3))  # to create an (3x3) array of random numbers between 1-10

array([[8, 7, 2],
       [8, 8, 9],
       [1, 9, 6]], dtype=int32)

In [15]:
x=np.array([[7,2,3],
            [2,5,2,],
            [3,5,1]])  # 2d array with 3 rows and 3 columns
y= np.array([[1,2,3],
            [4,5,6],
            [7,8,9]]) # 2d array with 3 rows and 3 columns
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(x+y)
print(x-y)
print(x*y)   # for 2d matrix this multiplication is doing element-to-element multiplication

[[ 8  4  6]
 [ 6 10  8]
 [10 13 10]]
[[ 6  0  0]
 [-2  0 -4]
 [-4 -3 -8]]
[[ 7  4  9]
 [ 8 25 12]
 [21 40  9]]


In [17]:
print(x@y)   # this method is used for actual matrix multiplication

[[36 48 60]
 [36 45 54]
 [30 39 48]]


In [18]:
np.dot(x,y)  #returns array after matrix multiplication

array([[36, 48, 60],
       [36, 45, 54],
       [30, 39, 48]])

In [19]:
np.prod(x)   #returns result after multiplying all the array elements,i.e.,---->(7*2*3*2*5*2*3*5*1=12600)

np.int64(12600)

In [20]:
x.mean() # returns mean of all array elements

np.float64(3.3333333333333335)

In [21]:
y.mean()

np.float64(5.0)

In [22]:
x.mean(axis=0)  # returns mean of array elements column-wise

array([4., 4., 2.])

In [23]:
y.mean(axis=1)  # returns mean of array elements row-wise

array([2., 5., 8.])

In [24]:
print(x.sum())  #returns sum of all array elements
print(x.var())   #returns variance of all array elements
print(x.std())   #returns deviation of all array elements

30
3.3333333333333335
1.8257418583505538


In [25]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25))  #25th percentile
print(np.percentile(a,50))  #50th percentile
print(np.percentile(a,75))  #75th percentile

3.0
5.0
7.0


In [26]:
b=np.array([[59,29,93,93],
            [84,60,30,66],
            [66,63,38,20],
            [31,32,61,92]])
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]
 [31 32 61 92]]


In [27]:
print('2x8')
print(b.reshape(2,8))

2x8
[[59 29 93 93 84 60 30 66]
 [66 63 38 20 31 32 61 92]]


In [28]:
print('8x2')
print(b.reshape(8,2))

8x2
[[59 29]
 [93 93]
 [84 60]
 [30 66]
 [66 63]
 [38 20]
 [31 32]
 [61 92]]


In [29]:
print(b)

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]
 [31 32 61 92]]


In [30]:
#indexing in array
print(b[0])   # printing first row of array
print(b[1])   # printing second row of array

[59 29 93 93]
[84 60 30 66]


In [31]:
print(b[0,1])   #printing element at first-row-second-column
print(b[0,0])

29
59


In [32]:
print(b[ :3]) # printing first 3 rows

[[59 29 93 93]
 [84 60 30 66]
 [66 63 38 20]]


In [33]:
print(b[3:]) #printing rows from 3rd onwards

[[31 32 61 92]]
