In [29]:
import numpy as np

#### How to create an array

In [30]:
a=np.array([1,2,3,4,5])  #list and array are almost same with only difference that there in array only same type of elements can be stored
b= np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [31]:
type(a)  # ndarray--> nth- dimensional array

numpy.ndarray

### Basic operations of Array

In [32]:
print(a+b)   #adding array elements
print(a-b)   #subtracting array elements
print(a*b)   #multiplying array elements

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [33]:
# creating 2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [34]:
# creating 3D array
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [35]:
print(a2.shape)
print(a3.shape) # two 2d arrays with 2 rows and 3 columns

(2, 3)
(2, 2, 3)


In [36]:
print(a2.ndim)
print(a3.ndim)

2
3


In [37]:
# creating a 4d array
a4 =np.array([[[[1,2],[3,4,]],
               [[5,6],[7,8]]],
              [[[9,10],[11,12]],
               [[13,14],[15,16]]]])
print(a4)
print(a4.shape)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
(2, 2, 2, 2)


In [38]:
print(a2.dtype)

int64


In [39]:
# arange() is used to create an array according to (start,stop,step) values similar to range()
np.arange(11)  #11 as it will count till 10 only(like range() 1 stop value is excluded)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
np.random.randint(1,11, size=(3,3))

array([[3, 2, 1],
       [6, 1, 1],
       [6, 5, 1]], dtype=int32)